#!/usr/bin/env python3
"""Rebuild prices.json from LiteLLM's live, community-maintained price database.

Usage:
  python update_prices.py            refresh prices for all models already tracked
  python update_prices.py NAME ...   also add these model ids

Prices are USD per 1 million tokens, in four token classes: in (fresh input),
cached_in (cache read), cache_write, out. Classes the source does not publish
are derived from the fresh-input rate and listed under "derived", so a guessed
rate is never mistaken for a published one. Standard library only.
"""

import json
import sys
import urllib.request
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ("https://raw.githubusercontent.com/BerriAI/litellm/main/"
          "model_prices_and_context_window.json")
PREFIXES = ["", "gemini/", "openai/", "anthropic/", "vertex_ai/", "openrouter/"]


def wanted_models():
    models = set()
    prices_file = ROOT / "prices.json"
    if prices_file.exists():
        old = json.loads(prices_file.read_text(encoding="utf-8"))
        models.update(k for k in old if not k.startswith("_"))
    for name in ("official", "community"):
        f = ROOT / "data" / f"{name}.json"
        if f.exists():
            for entry in json.loads(f.read_text(encoding="utf-8")):
                models.add(entry["model"])
    models.update(sys.argv[1:])
    return sorted(models)


def main():
    saved_path = ROOT / 'prices.json'
    saved = json.loads(saved_path.read_text(encoding='utf8')) if saved_path.exists() else {}
    print(f"Fetching {SOURCE} ...")
    with urllib.request.urlopen(SOURCE, timeout=120) as resp:
        db = json.loads(resp.read().decode("utf-8"))

    out = {"_comment": "USD per 1 million tokens, per token class: in (fresh input), "
                       "cached_in (cache read), cache_write, out. Auto-generated by "
                       "update_prices.py from LiteLLM's price database; edit only to override. "
                       "\"derived\" lists rates the source did not publish, computed as "
                       "in x 0.1 (cached_in) and in x 1.25 (cache_write).",
           "_source": SOURCE, "_retrieved": date.today().isoformat()}
    misses = []
    for model in wanted_models():
        if isinstance(saved.get(model), dict) and saved[model].get('manual_override'):
            out[model] = saved[model]
            print(f'  {model}: preserving sourced manual override')
            continue
        hit = None
        for prefix in PREFIXES:
            entry = db.get(prefix + model)
            if entry and "input_cost_per_token" in entry and "output_cost_per_token" in entry:
                hit = entry
                break
        if hit:
            fresh = round(hit["input_cost_per_token"] * 1e6, 4)
            rates, derived = {"in": fresh}, []
            for field, source_key, factor in (
                    ("cached_in", "cache_read_input_token_cost", 0.1),
                    ("cache_write", "cache_creation_input_token_cost", 1.25)):
                if hit.get(source_key) is not None:
                    rates[field] = round(hit[source_key] * 1e6, 6)
                else:
                    rates[field] = round(fresh * factor, 6)
                    derived.append(field)
            rates["out"] = round(hit["output_cost_per_token"] * 1e6, 4)
            out[model] = {**rates, "derived": sorted(derived)}
            print(f"  {model}: in ${rates['in']}/M, cached ${rates['cached_in']}/M, "
                  f"cache write ${rates['cache_write']}/M, out ${rates['out']}/M"
                  + (f"  (derived: {', '.join(sorted(derived))})" if derived else ""))
        else:
            misses.append(model)
            if model in saved:
                out[model] = saved[model]

    (ROOT / "prices.json").write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"Wrote prices.json with {len([k for k in out if not k.startswith('_')])} model(s).")
    if misses:
        print("Not found in the price database (add them to prices.json by hand):")
        for m in misses:
            print(f"  {m}")


if __name__ == "__main__":
    main()
